### ISSUE TITLE
Unable to find time() in C standard library

### ISSUE THREAD

**Issue by tanzislam** [TrustInSoft-CI/TrustInSoft-CI#12]
This is causing [Tests 10, 21, 26, 33 and 34](https://ci.trust-in-soft.com/projects/tanzislam/cryptopals-1/6) to have a "Missing function" error. Not sure why.

The necessary C standard header [`<time.h>`](https://en.cppreference.com/w/c/chrono/time) has been [`#include`-ed in `util-1.h`](https://github.com/tanzislam/cryptopals-1/blob/master/util-1.h#L11).

**Comment by guillaumemillot** [comment]
TIS CI requires the tests to be deterministic so the results are fully reproducible. Since `time` is not deterministic, TIS CI stops here and wants you to provide a body for this function. To fix that, you may stub the non-deterministic functions such as `time`, `srand` and `rand` in a separate helper file and add it to the `tis.config` file as follows:
https://github.com/tanzislam/cryptopals-1/compare/master...guillaumemillot:tis
