### ISSUE TITLE
"Action required" and wrong days shift

### ISSUE THREAD

**Issue by tankf33der** [TrustInSoft-CI/TrustInSoft-CI#18]
![image](https://user-images.githubusercontent.com/45243121/103363939-1833e900-4ac5-11eb-9b0f-0dbaba3428ad.png)

This is dashboard screenshot from [Monocypher](https://github.com/LoupVaillant/Monocypher/) project by @LoupVaillant.

I dont understand status of last two jobs:
- "Action required" - What should we do here? Should we care?
- dash as branch name, but commits were in "master" branch with "tag", maybe TIS-CI dont understand "tags"?
- wrong "50 days" shift

Maybe all above is important for project and devs should fix something.

**Comment by LoupVaillant** [comment]
Note: as far as I can see, lines 49 and 48 are spurious. Lines 47 and 46 show actual results, and all went well.

If there's anything to fix, it doesn't look urgent — at least not for me.  Though it sure is a little confusing.

**Comment by guillaumemillot** [comment]
@tankf33der and @LoupVaillant thank you for your feedback and I wish you all the best for this new year!

**1) Builds 49 and 48 : Action required**

I confirm TIS CI currently has a problem with tags: when a tag is created, a TIS CI build is created but it always fails with "Action required".
This unexpected behavior will be fixed in the next release (planned within a couple of weeks): a build will still be created but it shall be successful this time.

Are you happy if we display the tag name like this?

![image](https://user-images.githubusercontent.com/10330584/103525165-17150a00-4e7f-11eb-8a9e-f79932949ca6.png)

**2) Wrong "50 days" shift**

To me, the shift looks correct, see the correspond [commit](https://github.com/loupvaillant/Monocypher/commit/f298f422b80310b1168ab840f003e85dda249d51) on GitHub:

![image](https://user-images.githubusercontent.com/10330584/103525401-6fe4a280-4e7f-11eb-92a5-98b1539c4dcb.png)

**Comment by tankf33der** [comment]
- Tag name as branch is OK.
- "55 days of shadow" -

![image](https://user-images.githubusercontent.com/45243121/103527546-331ea880-4e8b-11eb-9a46-4532524967b0.png)

It was very easy to be confused because others tasks always equal.

**Comment by guillaumemillot** [comment]
Thanks! I'll update the issue after the fix is released.

**Comment by LoupVaillant** [comment]
Ah, I see why we had this shift: the commit really is 55 days old, but I only uploaded the tags recently. The date of the commit is correct indeed.

I'm happy with how the tag displays. It's nice to differentiate clearly between branch names and tag names.

_(Edit: oh, and, happy new year.)_

**Comment by guillaumemillot** [comment]
We've just pushed a new release. Tags and pull requests are now supported.
Changelog: https://docs.ci.trust-in-soft.com/changelog#2021-01-12

I'm closing the issue. Let me know if there's anything!
