### ISSUE TITLE
Sorting tests

### ISSUE THREAD

**Issue by tankf33der** [TrustInSoft-CI/TrustInSoft-CI#2]
This is my test [playground](https://ci.trust-in-soft.com/projects/tankf33der/monocypher-tis-ci/10).
I got a lot of 330 green tests and suspicious 38 non-green tests. OK.

I should be able to sort tests list or get any non-green tests on top of the list by default *or* implement feature - output only any non-green tests.

**Comment by tankf33der** [comment]
Those 38 non-green errors is _out of memory_ error for 16bit platforms, this is ok and expected **fat** functions. I will disable them completely.
```
...
[value] Analyzing a complete application starting at hidden
[value] Computing initial state
[value] Initial state computed
[value] The Analysis can be stopped with: kill -USR1 644
[kernel] Out of memory.
[info:results:computation] VERIF ERROR: unexpected error
````

**Comment by guillaumemillot** [comment]
Thanks Mike for your feedback and I confirm your finding. See the full results attached along with duration for each test: [tankf33der_monocypher-tis-ci_10.txt](https://github.com/TrustInSoft-CI/TrustInSoft-CI/files/4695272/tankf33der_monocypher-tis-ci_10.txt)

Next week, we're going to:
1) Display the first 1000 tests so you can see all your tests
2) Re-run the same job with 4GB allocation (instead of 2GB) to see if more tests pass

I'll update the issue once I get an update next week.

**Comment by guillaumemillot** [comment]
Since we released pagination/filtering (with few bugs still to be fixed), I'm closing the issue.
